name: new actions

on:
  push:
    branches:
    - main
    - release/*

  workflow_dispatch:

jobs:
  push-telegram:
    runs-on: ubuntu-latest
    needs: newevent
    steps:
      - name: Send to telegram
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            NEWS ${{github.event.issue.html_url}}


